application:
  name: FitnessClub

spring:
  datasource:
  url: jdbc:postgresql://localhost5432/fitness_club
  username: fitness
  password: mysecretpassword
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        format_sql: true
liquidbase:
  change-log: classpath:db/migration/db.changelog-master.xml

